MessagingApplication/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'CampaignController@index')->name('home');
Route::resource('campaign', 'CampaignController');
Route::get('start', ['as' => 'start', 'uses' => 'CampaignController@startAction']);
Route::get('stop', ['as' => 'stop', 'uses' => 'CampaignController@stopAction']);
Route::get('delete', ['as' => 'delete', 'uses' => 'CampaignController@deleteAction']);
Route::get('pause', ['as' => 'pause', 'uses' => 'CampaignController@pauseAction']);
Route::get('statusUpdate', ['as' => 'statusUpdate', 'uses' => 'CampaignController@statusUpdate']);
Route::get('responseUpdate', ['as' => 'responseUpdate', 'uses' => 'CampaignController@responseUpdate']);
Route::get('smsResponse', ['as' => 'smsResponse', 'uses' => 'CampaignController@smsResponse']);

MessagingApplication/app/Campaign.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Campaign extends Model
{
    protected $table = 'campaigns';
    protected $fillable = ['campaign_name', 'sms_text', 'schedule_date', 'status', 'is_delete','response'];
}

MessagingApplication/app/Http/Controllers/CampaignController.php
<?php

namespace App\Http\Controllers;

use App\Campaign;
use http\Env\Response;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Redirect;
use Maatwebsite\Excel\Facades\Excel;
use function MongoDB\BSON\fromJSON;
use function MongoDB\BSON\toJSON;
use Symfony\Component\HttpKernel\Client;
use Illuminate\Http\Resources\Json\Resource;

class CampaignController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['campaigns'] = Campaign::all();
        return view('campaign.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('campaign.create');

    }

    //for redirect to edit page
    public function edit($id)
    {
        $data['campaign'] = Campaign::find($id);
        return view('campaign.edit', $data);
    }

    public function update(Request $request, $id)
    {
        $data = array(
            'campaign_name' => $request->campaign_name,
            'sms_text' => $request->sms_text,
            'schedule_date' => $request->schedule_date,
        );

        Campaign::where('id', '=', $id)
            ->update($data);

        return Redirect::to('campaign');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $arr = array(
            'campaign_name' => $request->campaign_name,
            'sms_text' => $request->sms_text,
            'schedule_date' => $request->schedule_date,
            'status' => 0,
            'is_delete' => 0,
        );

        $created = Campaign::create($arr);

        $campaign_id = $created->id;
        $file = $request->file('csv_file');
        $this->importFile($file, $campaign_id);

        return redirect('/campaign');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['campaign'] = Campaign::find($id);
        $data['numbers'] = DB::table('numbers')
            ->where('campaign_id', '=', $id)
            ->get()
            ->pluck('number');

        return view('campaign.detail', $data);
    }

    //to import excel file that contain phone numbers
    public function importFile($file, $campaign_id)
    {

        $path = $file->getRealPath();
        $data = Excel::load($path, function ($reader) {
        })->get();
        if (!empty($data) && $data->count()) {
            foreach ($data as $key => $value) {
                $insert[] = [
                    'number' => $value->number,
                    'campaign_id' => $campaign_id,
                ];

            }
            if (!empty($insert)) {
                DB::table('numbers')->insert($insert);
                return 'data import successfully';
            }
        }

    }

//    for start button
    public function startAction(Request $request)
    {
        $campaign_id = Input::get('id');

        //phone_number form numbers table
        $phone_numbers = DB::table('numbers')
            ->where('campaign_id', '=', $campaign_id)
            ->get()
            ->pluck('number');

        //sms from campaign table of relavant id
        $sms_text = Campaign::where('id', '=', $campaign_id)
            ->get()
            ->pluck('sms_text');

        $phoneNumGroup = "";//initialize $phone number group
        for ($i = 0; $i < sizeof($phone_numbers); $i++) {
            $phone = $phone_numbers[$i];
            $phoneNumGroup = $phone . '+' . $phoneNumGroup;
        }
        $dataArr = array(
            'phoneNumGroup' => $phoneNumGroup,
            'sms_text' => $sms_text
        );
        return json_encode($dataArr);
    }

    //get response from server
    public function smsResponse(Request $request)
    {
        $url = Input::get('url');
        $file = file_get_contents($url);
        return $file;
    }

    //after clicking start button update status==1 :(1 means start)
    public function statusUpdate()
    {
        $campaign_id = Input::get('campaign_id');
        $data = array(
            'status' => 1
        );
        Campaign::where('id', '=', $campaign_id)
            ->update($data);
        return "status is sending";

    }

    //after getting response form server update response message
    public function responseUpdate()
    {
        $response = Input::get('response');
        $campaign_id = Input::get('campaign_id');
        $data = array(
            'response' => $response
        );
        Campaign::where('id', '=', $campaign_id)
            ->update($data);
        return "response is sending";

    }

    //status ==2 means stop
    public function stopAction()
    {
        $campaign_id = Input::get('id');;
        $data = array(
            'status' => 2
        );
        Campaign::where('id', '=', $campaign_id)
            ->update($data);
        return "status is stopping";

    }

//    is_delete==1 means not to display in index page but data will be in database
    public function deleteAction()
    {
        $campaign_id = Input::get('id');;
        $data = array(
            'is_delete' => 1
        );
        Campaign::where('id', '=', $campaign_id)
            ->update($data);
        return "deleting...";

    }

//    status==3 means pause
    public function pauseAction()
    {
        $campaign_id = Input::get('id');;
        $data = array(
            'status' => 3
        );
        Campaign::where('id', '=', $campaign_id)
            ->update($data);
        return "pausing...";
    }


}

MessagingApplication/resources/views/campaign/addNumber.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading"><h2>Add Campaign</h2></div>

                    <div class="panel-body">
                        {{--{{ route('import_parse') }}--}}
                        <form class="form-horizontal" method="POST" action="/import" enctype="multipart/form-data">
                            {{ csrf_field() }}

                            <div class="form-group{{ $errors->has('csv_file') ? ' has-error' : '' }}">


                                {{--<div class="col-md-6">--}}
                                    {{--<label for="campaign_name" class="col-md-4 control-label">Campaign Name:</label>--}}
                                    {{--<input id="campaign_name" type="text" class="form-control" name="campaign_name" required>--}}
                                {{--</div>--}}
                                {{--<div class="col-md-6">--}}
                                    {{--<label for="sms_text" class="col-md-4 control-label">SMS Text:</label>--}}
                                    {{--<textarea id="sms_text" name="sms_text" class="form-control" required>--}}
                                    {{--</textarea>--}}
                                {{--</div>--}}


                                <div class="col-md-6">
                                    <label for="csv_file" class="col-md-4 control-label">Mobile Number:</label>
                                    <input id="csv_file" type="file" class="form-control" name="csv_file" required>

                                    @if ($errors->has('csv_file'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('csv_file') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            {{--<div class="form-group">--}}
                                {{--<div class="col-md-6 col-md-offset-4">--}}
                                    {{--<div class="checkbox">--}}
                                        {{--<label>--}}
                                            {{--<input type="checkbox" name="header" checked> File contains header row?--}}
                                        {{--</label>--}}
                                    {{--</div>--}}
                                {{--</div>--}}
                            {{--</div>--}}

                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        submit
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

MessagingApplication/resources/views/campaign/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading"><h2>Add Campaign</h2></div>

                    <div class="panel-body">
                        {{--{{ route('import_parse') }}--}}
                        <form class="form-horizontal" method="POST" action="{{route('campaign.store')}}" enctype="multipart/form-data">
                            {{ csrf_field() }}

                            <div class="form-group{{ $errors->has('csv_file') ? ' has-error' : '' }}">


                                <div class="col-md-6">
                                    <label for="campaign_name" class="col-md-4 control-label">Campaign Name:</label>
                                    <input id="campaign_name" type="text" class="form-control" name="campaign_name"
                                           required>
                                </div>
                                <div class="col-md-6">
                                    <label for="sms_text" class="col-md-4 control-label">SMS Text:</label>
                                    <textarea id="sms_text" name="sms_text" class="form-control" required>
                                </textarea>
                                </div>

                                <div class="col-md-6">
                                    <label for="schedule_date" class="col-md-4 control-label">schedule date:</label>
                                    <input id="schedule_date" type="date" class="form-control" name="schedule_date"
                                           required>
                                </div>

                                <div class="col-md-6">
                                    <label for="csv_file" class="col-md-4 control-label">Mobile Number:</label>
                                    <input id="csv_file" type="file" class="form-control" name="csv_file" required>

                                    @if ($errors->has('csv_file'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('csv_file') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        submit
                                    </button>
                                    <a href="{{route('campaign.index')}}" type="submit" class="btn btn-danger">
                                        back
                                    </a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

MessagingApplication/resources/views/campaign/detail.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <a href="{{route('campaign.index')}}" class="btn btn-success pull-right">BACK</a>

                    </div>
                    <div class="card-body">
                        <div class="panel panel-default">
                            <div class="panel-heading"><h2>Campaign Detail</h2></div>
                            <div class="panel-heading"><h2>SN:{{$campaign->id}}</h2></div>
                            <table class="table">
                                <th>
                                <td>
                                    <label class="col-md-4 control-label"><b>Campaign Name:</b></label>
                                    <p>{{$campaign->campaign_name}}</p>
                                </td>
                                <td>
                                    <b>NUMBERS:</b>
                                    @forelse($numbers as $n)
                                        <span>{{$n}}</span></br>
                                    @empty
                                    @endforelse
                                </td>
                                </th>
                            </table>
                            <table class="table">

                                <tr>
                                    <label class="col-md-4 control-label"><b>SMS text:</b></label>
                                    <textarea id="sms_text" name="sms_text" class="form-control" readonly>
                                {{$campaign->sms_text}}
                                    </textarea>
                                </tr>
                                <tr>
                                    <label class="col-md-4 control-label"><b>Send date/time:</b></label>
                                    <p>{{$campaign->created_at}}</p>
                                </tr>
                                <tr>
                                    <label class="col-md-4 control-label"><b>Send status:</b></label>
                                    @if($campaign->status==1)
                                        <p>completed...</p>
                                    @elseif($campaign->status==2)
                                        <p>stopped...</p>
                                    @elseif($campaign->status==3)
                                        <p>paused...</p>
                                    @elseif($campaign->is_delete==1)
                                        <p>deleted...</p>
                                    @else
                                        <p>pending...</p>
                                    @endif
                                </tr>
                                <tr>
                                    <label class="col-md-4 control-label"><b>server response:</b></label>
                                    <p>{{$campaign->response}}</p>
                                </tr>
                                <tr>
                                    <label class="col-md-4 control-label"><b>Schedule date:</b></label>
                                    <p>{{$campaign->schedule_date}}</p>
                                </tr>

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

MessagingApplication/resources/views/campaign/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading"><h2>Edit Campaign</h2></div>

                    <div class="panel-body">
                        {{--{{ route('import_parse') }}--}}
                        {{ Form::model($campaign, array('method' => 'patch', 'route' => array('campaign.update', $campaign->id))) }}

                            <div class="col-md-6">
                                <label for="campaign_name" class="col-md-4 control-label">Campaign Name:</label>
                                {!! Form::text('campaign_name', $value = null, ['class'=>'form-control','required']) !!}

                            </div>
                            <div class="col-md-6">
                                <label for="sms_text" class="col-md-4 control-label">SMS Text:</label>
                                {!! Form::textarea('sms_text', $value = null, ['class'=>'form-control','required']) !!}

                            </div>

                            <div class="col-md-6">
                                <label for="schedule_date" class="col-md-4 control-label">schedule date:</label>
                                {!! Form::text('schedule_date', $value = null, ['class'=>'form-control','required']) !!}

                            </div>

                            {{--<div class="col-md-6">--}}
                            {{--<label for="csv_file" class="col-md-4 control-label">Mobile Number:</label>--}}
                            {{--<input id="csv_file" type="file" class="form-control" name="csv_file" required>--}}

                            {{--@if ($errors->has('csv_file'))--}}
                            {{--<span class="help-block">--}}
                            {{--<strong>{{ $errors->first('csv_file') }}</strong>--}}
                            {{--</span>--}}
                            {{--@endif--}}
                            {{--</div>--}}

                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    submit
                                </button>
                                <a href="{{route('campaign.index')}}" type="submit" class="btn btn-danger">
                                    back
                                </a>
                            </div>
                        </div>
                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

MessagingApplication/resources/views/campaign/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">
                        <a href="{{route('campaign.create')}}" class="btn btn-success pull-right">ADD Campaign</a>

                    </div>
                    <div class="card-body">
                        <table class="table table-striped table-bordered">
                            <thead>

                            <tr>
                                <th>campaign name</th>
                                <th>sms text</th>
                                <th>created date</th>
                                <th>schedule date</th>
                                <th>status</th>
                                <th>sta
                                    top
                                </th>
                                <th>pause | delete</th>
                                <th>report | edit</th>

                            </tr>
                            </thead>

                            <tbody>

                            @forelse($campaigns as $campaign)
                                @if($campaign->is_delete<>1)
                                    <tr>

                                        <td>{{$campaign->campaign_name}}</td>

                                        <td data-toggle="popover" data-content="{{$campaign->sms_text}}">
                                            {{substr($campaign->sms_text,-10)}}</td>

                                        <td>{{$campaign->created_at}}</td>

                                        <td>{{$campaign->schedule_date}}</td>
                                        @if($campaign->status==1)
                                            <td id="{{$campaign->id}}">completed....</td>
                                        @elseif($campaign->status==2)
                                            <td id="{{$campaign->id}}">stopped...</td>

                                        @elseif($campaign->status==3)
                                            <td id="{{$campaign->id}}">paused...</td>
                                        @else
                                            <td id="{{$campaign->id}}">pending...</td>
                                        @endif

                                        <td>
                                            <button href="" id="start{{$campaign->id}}"
                                                    onclick="start({{$campaign->id}})"
                                                    class="btn btn-info btn-xs {{$campaign->id}}"><label
                                                        class="glyphicon glyphicon-pencil"></label>start
                                            </button>
                                            <br/><br/>
                                            <button href="" id="stop{{$campaign->id}}" onclick="stop({{$campaign->id}})"
                                                    class="btn btn-success btn-xs {{$campaign->id}}"><label
                                                        class="glyphicon glyphicon-eye-open"></label>stop
                                            </button>
                                        </td>
                                        <td>
                                            <button href="" id="pause{{$campaign->id}}"
                                                    onclick="pause({{$campaign->id}});"
                                                    class="btn btn-info btn-xs {{$campaign->id}}"><label
                                                        class="glyphicon glyphicon-pencil"></label>pause
                                            </button>
                                            <br/><br/>
                                            <button href="" id="delete{{$campaign->id}}"
                                                    onclick="deleteMark({{$campaign->id}})"
                                                    class="btn btn-danger btn-xs {{$campaign->id}}"><label
                                                        class="glyphicon glyphicon-pencil"></label>delete
                                            </button>

                                        </td>
                                        <td>
                                            <a href="{{route('campaign.show', array($campaign->id))}}"
                                               class="btn btn-primary pull-right">report</a><br/><br/>
                                            <a href="{{route('campaign.edit', array($campaign->id))}}"
                                               class="btn btn-primary pull-right">edit</a>
                                        </td>

                                    </tr>
                                    @if($campaign->status==1)
                                        <script>
                                            $("#start{{$campaign->id}}").prop('disabled', true);
                                        </script
                                    @elseif($campaign->status==2)
                                        <script>
                                            {{--alert("#start{{$campaign->id}}");--}}
                                            $(".{{$campaign->id}}").prop('disabled', true);
                                        </script>
                                    @endif
                                @endif
                            @empty
                                <tr>
                                    <td colspan="15">
                                        <p class="text-danger text-center"><b>No data found !</b></p>
                                    </td>

                                </tr>
                            @endforelse

                            </tbody>

                        </table>
                    </div>
                </div>
            </div>
        </div>

@endsection